# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12

  # Pre-commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
        name: "Can't commit to main"
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # Checker
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [
          'pep8-naming==0.11.1',
        ]
